import nextCoreWebVitals from "eslint-config-next/core-web-vitals";

// - Next 16 removed `next lint`, so ESLint is configured directly here
const eslintConfig = [
  {
    ignores: [
      ".next/**",
      "out/**",
      "build/**",
      "node_modules/**",
      // - Generated by `npx convex dev`, not ours to lint
      "convex/_generated/**",
      // - Committed notes/vaults, not application code
      "obsidianNotes/**",
      ".unotes/**",
    ],
  },
  ...nextCoreWebVitals,
];

export default eslintConfig;
